In [52]:
import pandas as pd
import tensorflow as tf
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import numpy as np

In [53]:
data = pd.read_csv('house_prices.csv')
data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [54]:
data.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [55]:
columns = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [56]:
columns

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [57]:
data = pd.read_csv('house_prices.csv', usecols = columns)

In [58]:
data.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [59]:
scaler_x = MinMaxScaler()
data[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(data[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [60]:
data.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [61]:
scaler_y = MinMaxScaler()
data[['price']] = scaler_y.fit_transform(data[['price']])

In [62]:
data.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [63]:
X = data.drop('price', axis = 1)
y = data.price

In [64]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [65]:
type(X)

pandas.core.frame.DataFrame

In [66]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [67]:
type(y)

pandas.core.series.Series

In [68]:
predict_columns = columns[1:17]
predict_columns

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [69]:
columns_1 = [tf.feature_column.numeric_column(key = c) for c in predict_columns]

In [70]:
print(columns_1[10])

_NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [72]:
X_train.shape

(15129, 16)

In [73]:
y_train.shape

(15129,)

In [74]:
X_test.shape

(6484, 16)

In [75]:
train_function = tf.estimator.inputs.pandas_input_fn(x = X_train, y = y_train,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [76]:
test_function = tf.estimator.inputs.pandas_input_fn(x = X_test, y = y_test,
                                                   batch_size = 32, num_epochs = 10000, shuffle = False)

In [77]:
regressor = tf.estimator.LinearRegressor(feature_columns=columns_1)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\JOELPI~1\\AppData\\Local\\Temp\\tmp0sk3we1b', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001431F7B6C88>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [78]:
regressor.train(input_fn=train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\JOELPI~1\AppData\Local\Temp\tmp0sk3we1b\model.ckpt.
INFO:tensorflow:loss = 0.2606005, step = 0
INFO:tensorflow:global_step/sec: 71.6311
INFO:tensorflow:loss = 0.10652466, step = 100 (1.400 sec)
INFO:tensorflow:global_step/sec: 79.5125
INFO:tensorflow:loss = 0.018953964, step = 200 (1.263 sec)
INFO:tensorflow:global_step/sec: 81.3197
INFO:tensorflow:loss = 0.013940003, step = 300 (1.227 sec)
INFO:tensorflow:global_step/sec: 87.7668
INFO:tensorflow:loss = 0.009793522, step = 400 (1.137 sec)
INFO:tensorflow:global_step/sec: 75.2711
INFO:tensorflow:loss = 0.010965925, step = 500 (1.332 sec)
INFO:tensorflow:global_step/sec: 85.7389
INFO:tensorflow:loss = 0.026426883, step = 600 (1.164 sec)
INFO:tensorflo

INFO:tensorflow:global_step/sec: 59.7589
INFO:tensorflow:loss = 0.015799085, step = 7900 (1.679 sec)
INFO:tensorflow:global_step/sec: 61.6717
INFO:tensorflow:loss = 0.015282055, step = 8000 (1.617 sec)
INFO:tensorflow:global_step/sec: 64.9081
INFO:tensorflow:loss = 0.016684853, step = 8100 (1.543 sec)
INFO:tensorflow:global_step/sec: 69.8891
INFO:tensorflow:loss = 0.051050015, step = 8200 (1.430 sec)
INFO:tensorflow:global_step/sec: 77.996
INFO:tensorflow:loss = 0.02263485, step = 8300 (1.280 sec)
INFO:tensorflow:global_step/sec: 75.8696
INFO:tensorflow:loss = 0.01914258, step = 8400 (1.319 sec)
INFO:tensorflow:global_step/sec: 75.498
INFO:tensorflow:loss = 0.0108610075, step = 8500 (1.323 sec)
INFO:tensorflow:global_step/sec: 76.6532
INFO:tensorflow:loss = 0.012950991, step = 8600 (1.304 sec)
INFO:tensorflow:global_step/sec: 75.0737
INFO:tensorflow:loss = 0.021499975, step = 8700 (1.352 sec)
INFO:tensorflow:global_step/sec: 65.2889
INFO:tensorflow:loss = 0.017631654, step = 8800 (1.52

In [79]:
train_metrics = regressor.evaluate(input_fn=train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-17-21:21:23
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmp0sk3we1b\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-01-17-21:22:36
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007933177, global_step = 10000, loss = 0.025386166


In [80]:
test_metrics = regressor.evaluate(input_fn=test_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-17-21:22:37
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmp0sk3we1b\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-01-17-21:24:05
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00090051163, global_step = 10000, loss = 0.028816372


In [81]:
train_metrics

{'average_loss': 0.0007933177, 'loss': 0.025386166, 'global_step': 10000}

In [82]:
test_metrics

{'average_loss': 0.00090051163, 'loss': 0.028816372, 'global_step': 10000}

In [83]:
prediction_function = tf.estimator.inputs.pandas_input_fn(x = X_test, shuffle = False)

In [84]:
predictions = regressor.predict(input_fn=prediction_function)

In [85]:
list(predictions)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmp0sk3we1b\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.03819853], dtype=float32)},
 {'predictions': array([0.04192863], dtype=float32)},
 {'predictions': array([0.0332937], dtype=float32)},
 {'predictions': array([0.01237651], dtype=float32)},
 {'predictions': array([0.0132811], dtype=float32)},
 {'predictions': array([0.09012904], dtype=float32)},
 {'predictions': array([0.01803054], dtype=float32)},
 {'predictions': array([0.02673829], dtype=float32)},
 {'predictions': array([0.04070488], dtype=float32)},
 {'predictions': array([0.03202348], dtype=float32)},
 {'predictions': array([0.03562474], dtype=float32)},
 {'predictions': array([0.06024093], dtype=float32)},
 {'predictions': array([-0.0092091], dtype=float32)},
 {'predictions': array([0.07078933], dtype=float32)},
 {'predictions': array([0.06234873], dtype=float32)},
 {'predictions': array([0.07761342], dtype=float32)},
 {'predictions': array([0.01979928], dtype=float32)},
 {'predictions': array([0.03688399], dtype=float32)},
 {'predictions': array([0.0110

In [86]:
valores_predictions = []
for p in regressor.predict(input_fn=prediction_function):
    valores_predictions.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmp0sk3we1b\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [87]:
valores_predictions

[array([0.03819853], dtype=float32),
 array([0.04192863], dtype=float32),
 array([0.0332937], dtype=float32),
 array([0.01237651], dtype=float32),
 array([0.0132811], dtype=float32),
 array([0.09012904], dtype=float32),
 array([0.01803054], dtype=float32),
 array([0.02673829], dtype=float32),
 array([0.04070488], dtype=float32),
 array([0.03202348], dtype=float32),
 array([0.03562474], dtype=float32),
 array([0.06024093], dtype=float32),
 array([-0.0092091], dtype=float32),
 array([0.07078933], dtype=float32),
 array([0.06234873], dtype=float32),
 array([0.07761342], dtype=float32),
 array([0.01979928], dtype=float32),
 array([0.03688399], dtype=float32),
 array([0.01100073], dtype=float32),
 array([0.06104083], dtype=float32),
 array([0.03175187], dtype=float32),
 array([0.12876886], dtype=float32),
 array([0.02035458], dtype=float32),
 array([0.10114836], dtype=float32),
 array([0.04065308], dtype=float32),
 array([-0.01435899], dtype=float32),
 array([0.03867003], dtype=float32),
 a

In [88]:
valores_predictions = np.asarray(valores_predictions).reshape(-1,1)

In [89]:
valores_predictions

array([[0.03819853],
       [0.04192863],
       [0.0332937 ],
       ...,
       [0.05085907],
       [0.01502763],
       [0.03849138]], dtype=float32)

In [90]:
valores_predictions = scaler_y.inverse_transform(valores_predictions)
valores_predictions

array([[366263.8 ],
       [394705.78],
       [328864.47],
       ...,
       [462800.44],
       [189585.66],
       [368496.75]], dtype=float32)

In [91]:
y_test

3959     0.050492
16061    0.047541
14140    0.030466
16224    0.018361
9523     0.038033
           ...   
14969    0.030557
12660    0.039993
14663    0.072787
8852     0.028328
20673    0.072131
Name: price, Length: 6484, dtype: float64

In [92]:
y_test.shape

(6484,)

In [93]:
y_test2 = y_test.values.reshape(-1,1)
y_test2.shape

(6484, 1)

In [94]:
y_test2 = scaler_y.inverse_transform(y_test2)

In [95]:
y_test2

array([[460000.],
       [437500.],
       [307300.],
       ...,
       [630000.],
       [291000.],
       [625000.]])

In [96]:
mae = mean_absolute_error(y_test2, valores_predictions)

In [97]:
mae

141358.26762527568