In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

C:\Users\Joel Pires\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Joel Pires\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Joel Pires\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Joel Pires\AppData\Roaming\P

In [2]:
data = pd.read_csv('house_prices.csv')
data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [3]:
data.shape

(21613, 21)

In [4]:
X = data.iloc[:, 5:6].values
y = data.iloc[:, 2:3].values

In [5]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [6]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [7]:
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

In [8]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [9]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [10]:
columns = [tf.feature_column.numeric_column('x', shape = [1])]

In [11]:
columns

[_NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [12]:
regressor = tf.estimator.LinearRegressor(feature_columns=columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\JOELPI~1\\AppData\\Local\\Temp\\tmpaxpqdag0', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001B914AEE828>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [14]:
X_train.shape

(15129, 1)

In [15]:
y_train.shape

(15129, 1)

In [16]:
X_test.shape

(6484, 1)

In [17]:
y_test.shape

(6484, 1)

In [18]:
train_function = tf.estimator.inputs.numpy_input_fn({'x': X_train}, y_train,
                                                        batch_size = 32, num_epochs = None, 
                                                        shuffle = True)

In [19]:
test_function = tf.estimator.inputs.numpy_input_fn({'x': X_test}, y_test, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [20]:
regressor.train(input_fn = train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\JOELPI~1\AppData\Local\Temp\tmpaxpqdag0\model.ckpt.
INFO:tensorflow:loss = 16.11892, step = 0
INFO:tensorflow:global_step/sec: 196.443
INFO:tensorflow:loss = 9.274247, step = 100 (0.515 sec)
INFO:tensorflow:global_step/sec: 151.11
INFO:tensorflow:loss = 14.227766, step = 200 (0.663 sec)
INFO:tensorflow:global_step/sec: 80.0845
INFO:tensorflow:loss = 12.389596, step = 300 (1.248 sec)
INFO:tensorflow:global_step/sec: 198.979
INFO:tensorflow:loss = 12.653597, step = 400 (0.501 sec)
INFO:tensorflow:global_step/sec: 210.033
INFO:tensorflow:loss = 32.617188, step = 500 (0.516 sec)
INFO:tensorflow:global_step/sec: 193.409
INFO:tensorflow:loss = 24.431967, step = 600 (0.476 sec)
INFO:tensorflow:global_step/

INFO:tensorflow:loss = 10.88394, step = 8000 (0.362 sec)
INFO:tensorflow:global_step/sec: 255.904
INFO:tensorflow:loss = 12.073667, step = 8100 (0.389 sec)
INFO:tensorflow:global_step/sec: 264.344
INFO:tensorflow:loss = 5.7069674, step = 8200 (0.378 sec)
INFO:tensorflow:global_step/sec: 262.61
INFO:tensorflow:loss = 9.8531275, step = 8300 (0.382 sec)
INFO:tensorflow:global_step/sec: 301.765
INFO:tensorflow:loss = 12.345152, step = 8400 (0.329 sec)
INFO:tensorflow:global_step/sec: 292.94
INFO:tensorflow:loss = 14.69666, step = 8500 (0.342 sec)
INFO:tensorflow:global_step/sec: 298.616
INFO:tensorflow:loss = 15.70563, step = 8600 (0.337 sec)
INFO:tensorflow:global_step/sec: 302.677
INFO:tensorflow:loss = 11.762901, step = 8700 (0.329 sec)
INFO:tensorflow:global_step/sec: 295.533
INFO:tensorflow:loss = 12.35478, step = 8800 (0.337 sec)
INFO:tensorflow:global_step/sec: 279.458
INFO:tensorflow:loss = 8.288596, step = 8900 (0.362 sec)
INFO:tensorflow:global_step/sec: 237.972
INFO:tensorflow:l

In [21]:
train_metrics = regressor.evaluate(input_fn = train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-17-21:28:59
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmpaxpqdag0\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-01-17-21:29:23
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.4991989, global_step = 10000, loss = 15.974365


In [22]:
test_metrics = regressor.evaluate(input_fn = test_function, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-17-21:29:24
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmpaxpqdag0\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-01-17-21:29:54
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5257142, global_step = 10000, loss = 16.822855


In [23]:
train_metrics

{'average_loss': 0.4991989, 'loss': 15.974365, 'global_step': 10000}

In [24]:
test_metrics

{'average_loss': 0.5257142, 'loss': 16.822855, 'global_step': 10000}

In [25]:
new_houses = np.array([[800], [900], [1000]])
new_houses

array([[ 800],
       [ 900],
       [1000]])

In [26]:
new_houses = scaler_x.transform(new_houses)
new_houses

array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [27]:
predict_function = tf.estimator.inputs.numpy_input_fn({'x': new_houses}, shuffle = False)

In [28]:
predictions = regressor.predict(input_fn = predict_function)

In [29]:
predictions

<generator object Estimator.predict at 0x000001B93A62FBF8>

In [30]:
list(predictions)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmpaxpqdag0\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.9730472], dtype=float32)},
 {'predictions': array([-0.8965389], dtype=float32)},
 {'predictions': array([-0.82003057], dtype=float32)}]

In [31]:
for p in regressor.predict(input_fn = predict_function):
    print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JOELPI~1\AppData\Local\Temp\tmpaxpqdag0\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[-0.9730472]
[182864.33]
[-0.8965389]
[210951.92]
[-0.82003057]
[239039.58]
