In [1]:
import tensorflow as tf

C:\Users\Joel Pires\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Joel Pires\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Joel Pires\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Joel Pires\AppData\Roaming\P

In [2]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

In [3]:
sum = a + b

In [4]:
type(a)

tensorflow.python.framework.ops.Tensor

In [5]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [6]:
with tf.Session() as sess:
    print(sess.run(sum))

[10 10 10]


In [7]:
temp_a = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'temp_a')

In [8]:
type(temp_a)

tensorflow.python.framework.ops.Tensor

In [9]:
print(temp_a)

Tensor("temp_a:0", shape=(2, 3), dtype=int32)


In [10]:
temp_a.shape

TensorShape([Dimension(2), Dimension(3)])

In [11]:
temp_b = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'temp_b')

In [12]:
sum1 = tf.add(temp_a, temp_b)

In [13]:
with tf.Session() as sess:
    print(sess.run(temp_a))
    print('\n')
    print(sess.run(temp_b))
    print('\n')
    print(sess.run(sum1))

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]]


[[ 2  4  6]
 [ 8 10 12]]


In [14]:
a2 = tf.constant([[1,2,3], [4,5,6]])
b2 = tf.constant([[1], [2]])
sum2 = tf.add(a2, b2)

In [15]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')
    print(sess.run(sum2))

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


[[2 3 4]
 [6 7 8]]
